name = "long-snow-3188"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# OpenNext build output entry point
main = ".open-next/worker.js"

# Static assets produced by OpenNext
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "rental-management"
database_id = "abbc447e-472e-429d-b84b-c8a5c24bfa49"
